/*
 * MUSART_Config.h
 *
 *  Created on: Nov 25, 2022
 *      Author: medo
 */

#ifndef MCAL_MUSART_MUSART_CONFIG_H_
#define MCAL_MUSART_MUSART_CONFIG_H_

/*Options For Operating Mode
 *
 *1-MUSART_ASYNCHRONOUS_MODE
 *1-MUSART_SYNCHRONOUS_MODE
 *
 **/
#define MUSART_OPERATING_MODE MUSART_ASYNCHRONOUS_MODE

/*Options For PARITY BIT
 *
 *1-MUSART_PARITY_DISABLED
 *1-MUSART_PARITY_EVEN
 *1-MUSART_PARITY_ODD
 *
 **/

#define MUSART_PARITY_MODE MUSART_PARITY_DISABLED


/*Options For STOP BITS
 *
 *1-MUSART_ONE_STOP_BIT
 *1-MUSART_TWO_STOP_BIT
 **/

#define MUSART_STOP_MODE MUSART_ONE_STOP_BIT

/*Options For DATA BITS
 *
 *1-MUSART_FIVE_DATA_BITS
 *2-MUSART_SIX_DATA_BITS
 *3-MUSART_SEVEN_DATA_BITS
 *4-MUSART_EIGHT_DATA_BITS
 *5-MUSART_NINE_DATA_BITS
 **/

#define MUSART_DATA_SIZE MUSART_EIGHT_DATA_BITS


/*Options For BAUD RATE
 *
 *1-MUSART_2400
 *2-MUSART_4800
 *3-MUSART_9600
 *4-MUSART_19200
 *5-MUSART_38400
 **/

#define MUSART_BAUD_RATE MUSART_9600



#endif /* MCAL_MUSART_MUSART_CONFIG_H_ */
